import { UnifiedTeamMember } from './types'

export const INITIAL_MEMBERS_DATA_B: UnifiedTeamMember[] = [
  {
    id: 'rec-lead-3',
    name: 'Nina Brooks',
    email: 'n.brooks@talentflow.io',
    avatar: 'N',
    role: 'Lead Recruiter — EV & Tech Sourcing',
    isTeamLead: true,
    teamLead: 'Nina Brooks (Self)',
    clientNames: ['Tesla'],
    totalRequirements: 28,
    totalSubmissions: 84,
    tatDays: 2.0,
    totalInterviews: 20,
    performanceStatus: 'Top Performer',
    membersCount: 3,
    teamMembers: ['rahimoon Shaik', 'Adirala sathvika', 'Charlie Darwin'],
  },
  {
    id: 'rec-8',
    name: 'rahimoon Shaik',
    email: 'rahimoon.s@talentflow.io',
    avatar: 'R',
    role: 'Automotive Sourcing Specialist',
    isTeamLead: false,
    teamLead: 'Nina Brooks',
    clientNames: ['Tesla'],
    totalRequirements: 14,
    totalSubmissions: 42,
    tatDays: 2.0,
    totalInterviews: 11,
    performanceStatus: 'Top Performer',
  },
  {
    id: 'rec-9',
    name: 'Adirala sathvika',
    email: 'adirala.s@talentflow.io',
    avatar: 'A',
    role: 'Software Recruiter',
    isTeamLead: false,
    teamLead: 'Nina Brooks',
    clientNames: ['Tesla'],
    totalRequirements: 8,
    totalSubmissions: 22,
    tatDays: 2.5,
    totalInterviews: 5,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-10',
    name: 'Charlie Darwin',
    email: 'charlie.d@talentflow.io',
    avatar: 'C',
    role: 'Technical Sourcing Lead',
    isTeamLead: false,
    teamLead: 'Nina Brooks',
    clientNames: ['Tesla'],
    totalRequirements: 6,
    totalSubmissions: 20,
    tatDays: 2.2,
    totalInterviews: 4,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-lead-4',
    name: 'Ray Diaz',
    email: 'ray.d@talentflow.io',
    avatar: 'R',
    role: 'Lead Recruiter — Enterprise SAP & ERP',
    isTeamLead: true,
    teamLead: 'Ray Diaz (Self)',
    clientNames: ['ITC Limited'],
    totalRequirements: 24,
    totalSubmissions: 72,
    tatDays: 2.3,
    totalInterviews: 18,
    performanceStatus: 'On Track',
    membersCount: 3,
    teamMembers: ['Harini Sindey', 'Viswanath Reddy', 'Rachana Golkonda'],
  },
  {
    id: 'rec-11',
    name: 'Harini Sindey',
    email: 'harini.s@talentflow.io',
    avatar: 'H',
    role: 'Enterprise Recruiter',
    isTeamLead: false,
    teamLead: 'Ray Diaz',
    clientNames: ['ITC Limited'],
    totalRequirements: 10,
    totalSubmissions: 32,
    tatDays: 2.1,
    totalInterviews: 8,
    performanceStatus: 'On Track',
  },
  {
    id: 'rec-12',
    name: 'Viswanath Reddy',
    email: 'viswanath.r@talentflow.io',
    avatar: 'V',
    role: 'SAP Recruiter',
    isTeamLead: false,
    teamLead: 'Ray Diaz',
    clientNames: ['ITC Limited'],
    totalRequirements: 8,
    totalSubmissions: 24,
    tatDays: 2.6,
    totalInterviews: 6,
    performanceStatus: 'On Track',
  },
]
