import { ActivityLogItem } from '../../../types'

export const INITIAL_LOGS: ActivityLogItem[] = [
  {
    id: 'LOG-1001',
    timestamp: 'Today at 02:45 PM',
    userName: 'Harish Gadipally',
    userEmail: 'harish.g@metaforgeit.com',
    userRole: 'lead',
    userAvatar: 'H',
    action: 'Assigned Requirement REQ-2026-08-12-001 (Lead Java Full Stack) to Marcus Chen',
    category: 'Requirements',
    targetEntity: 'Requirement REQ-2026-08-12-001',
    targetId: 'REQ-2026-08-12-001',
    clientName: 'Accenture',
    ipAddress: '192.168.1.45',
    status: 'Success',
    details: 'Assigned requirement REQ-2026-08-12-001 for Accenture to team member Marcus Chen with high priority SLA.',
  },
  {
    id: 'LOG-1002',
    timestamp: 'Today at 01:20 PM',
    userName: 'Harish Gadipally',
    userEmail: 'harish.g@metaforgeit.com',
    userRole: 'lead',
    userAvatar: 'H',
    action: 'Cross-assigned Requirement REQ-2026-08-12-004 to Suresh kulkarni',
    category: 'Requirements',
    targetEntity: 'Requirement REQ-2026-08-12-004',
    targetId: 'REQ-2026-08-12-004',
    clientName: 'Accenture',
    ipAddress: '192.168.1.45',
    status: 'Success',
    details: 'Cross-client requirement assignment performed in My Team page for Accenture account.',
  },
  {
    id: 'LOG-2001',
    timestamp: 'Today at 01:45 PM',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'M',
    action: 'Submitted Candidate CAND-001 (Priya Nair) for REQ-2026-08-12-001',
    category: 'Submissions',
    targetEntity: 'Candidate CAND-001',
    targetId: 'CAND-001',
    clientName: 'Accenture',
    ipAddress: '192.168.1.45',
    status: 'Success',
    details: 'Submitted candidate profile with resume attachment for Lead Java Developer role at Accenture.',
  },
  {
    id: 'LOG-2002',
    timestamp: 'Today at 09:15 AM',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'M',
    action: 'Logged into Recruiter Application Portal',
    category: 'System & Access',
    targetEntity: 'User Session',
    targetId: 'LGN-9001',
    clientName: '',
    ipAddress: '192.168.1.45',
    status: 'Success',
    details: 'Successful authentication via 2FA. Session token issued for 8 hours.',
  },
  {
    id: 'LOG-3001',
    timestamp: 'Today at 10:15 AM',
    userName: 'David Park',
    userEmail: 'd.park@talentflow.io',
    userRole: 'admin',
    userAvatar: 'D',
    action: 'Updated Client SLA settings for Accenture Account',
    category: 'Client Management',
    targetEntity: 'Client Accenture',
    targetId: 'CLI-001',
    clientName: 'Accenture',
    ipAddress: '192.168.1.5',
    status: 'Success',
    details: 'Updated SLA requirement response threshold to 48 hours for Accenture global account.',
  },

  // YESTERDAY (Sep 08, 2026)
  {
    id: 'LOG-3002',
    timestamp: 'Sep 08, 2026 at 04:30 PM',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'M',
    action: 'Sourced candidate Alex Turner (Senior React Developer) for Accenture',
    category: 'Candidate Sourcing',
    targetEntity: 'Candidate CAND-002',
    targetId: 'CAND-002',
    clientName: 'Accenture',
    ipAddress: '192.168.1.45',
    status: 'Success',
    details: 'Uploaded candidate CV and performed AI skill extraction.',
  },
  {
    id: 'LOG-3003',
    timestamp: 'Sep 08, 2026 at 02:15 PM',
    userName: 'Priya Sharma',
    userEmail: 'p.sharma@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'P',
    action: 'Submitted Candidate Rohan Varma for REQ-2026-08-12-003',
    category: 'Submissions',
    targetEntity: 'Candidate CAND-008',
    targetId: 'CAND-008',
    clientName: 'Deloitte',
    ipAddress: '192.168.1.52',
    status: 'Success',
    details: 'Submitted profile to Lead Lakshmi V for review.',
  },
  {
    id: 'LOG-3004',
    timestamp: 'Sep 08, 2026 at 11:00 AM',
    userName: 'Suresh kulkarni',
    userEmail: 'suresh.k@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'S',
    action: 'Scheduled Technical Interview Round 1 for Vikram Mehta',
    category: 'Interviews',
    targetEntity: 'Candidate CAND-004',
    targetId: 'CAND-004',
    clientName: 'Accenture',
    ipAddress: '192.168.1.60',
    status: 'Success',
    details: 'Scheduled interview panel with Accenture Tech Manager.',
  },

  // PREVIOUS DAYS (Sep 07, Sep 06, Sep 05)
  {
    id: 'LOG-4001',
    timestamp: 'Sep 07, 2026 at 03:45 PM',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'M',
    action: 'Sourced candidate Rania Khalil for Node.js Backend requirement',
    category: 'Candidate Sourcing',
    targetEntity: 'Candidate CAND-003',
    targetId: 'CAND-003',
    clientName: 'Accenture',
    ipAddress: '192.168.1.45',
    status: 'Success',
    details: 'Added profile details with 7 yrs Node.js experience.',
  },
  {
    id: 'LOG-4002',
    timestamp: 'Sep 07, 2026 at 10:30 AM',
    userName: 'Harish Gadipally',
    userEmail: 'harish.g@metaforgeit.com',
    userRole: 'lead',
    userAvatar: 'H',
    action: 'Assigned 3 new backend requirements to Priya Sharma',
    category: 'Requirements',
    targetEntity: 'Requirement REQ-2026-08-10-002',
    targetId: 'REQ-2026-08-10-002',
    clientName: 'Deloitte',
    ipAddress: '192.168.1.10',
    status: 'Success',
    details: 'Allocated Deloitte requirements for rapid sourcing.',
  },
  {
    id: 'LOG-5001',
    timestamp: 'Sep 06, 2026 at 04:15 PM',
    userName: 'Priya Sharma',
    userEmail: 'p.sharma@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'P',
    action: 'Updated candidate interview feedback for candidate Ananya Sharma',
    category: 'Interviews',
    targetEntity: 'Candidate CAND-005',
    targetId: 'CAND-005',
    clientName: 'Accenture',
    ipAddress: '192.168.1.52',
    status: 'Success',
    details: 'Logged Client Manager feedback: Passed Round 1 with high score.',
  },
  {
    id: 'LOG-6001',
    timestamp: 'Sep 05, 2026 at 02:00 PM',
    userName: 'Suresh kulkarni',
    userEmail: 'suresh.k@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'S',
    action: 'Exported Sourcing Performance Report for Aug 2026',
    category: 'User Management',
    targetEntity: 'Reporting Engine',
    targetId: 'REP-550',
    clientName: '',
    ipAddress: '192.168.1.60',
    status: 'Success',
    details: 'Downloaded performance metrics CSV.',
  },
]
