import { RecruiterLoginRecord } from './types'

export const LOGIN_RECORDS_TODAY: RecruiterLoginRecord[] = [
  {
    id: 'LGN-9001',
    userName: 'Marcus Chen',
    userEmail: 'm.chen@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'M',
    firstEverLoginTimestamp: 'Jan 12, 2026 at 08:30:00 AM',
    logDate: 'Today (Sep 09, 2026)',
    loginTime: '09:15:22 AM',
    logoutTime: 'Active Session (Logged in now)',
    sessionDuration: '4h 32m',
    activeScreenTime: '2h 52m',
    ipAddress: '192.168.1.45',
    deviceInfo: 'Windows 11 / Chrome 128',
    status: 'Active Now',
    actionsLoggedCount: 14,
  },
  {
    id: 'LGN-9004',
    userName: 'Priya Sharma',
    userEmail: 'p.sharma@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'P',
    firstEverLoginTimestamp: 'Feb 01, 2026 at 09:00:00 AM',
    logDate: 'Today (Sep 09, 2026)',
    loginTime: '09:30:15 AM',
    logoutTime: 'Active Session (Logged in now)',
    sessionDuration: '4h 17m',
    activeScreenTime: '2h 15m',
    ipAddress: '192.168.1.52',
    deviceInfo: 'macOS Sonoma / Safari 17',
    status: 'Active Now',
    actionsLoggedCount: 9,
  },
  {
    id: 'LGN-9006',
    userName: 'Suresh kulkarni',
    userEmail: 'suresh.k@talentflow.io',
    userRole: 'recruiter',
    userAvatar: 'S',
    firstEverLoginTimestamp: 'Mar 15, 2026 at 09:15:00 AM',
    logDate: 'Today (Sep 09, 2026)',
    loginTime: '09:45:00 AM',
    logoutTime: 'Active Session (Logged in now)',
    sessionDuration: '4h 02m',
    activeScreenTime: '1h 48m',
    ipAddress: '192.168.1.60',
    deviceInfo: 'Windows 11 / Edge 127',
    status: 'Active Now',
    actionsLoggedCount: 6,
  },
  {
    id: 'LGN-9008',
    userName: 'lakshmi.v Recruiter',
    userEmail: 'lakshmi.v@talentflow.io',
    userRole: 'lead',
    userAvatar: 'L',
    firstEverLoginTimestamp: 'Jan 05, 2026 at 08:45:00 AM',
    logDate: 'Today (Sep 09, 2026)',
    loginTime: '09:05:10 AM',
    logoutTime: 'Active Session (Logged in now)',
    sessionDuration: '4h 42m',
    activeScreenTime: '3h 10m',
    ipAddress: '10.0.4.18',
    deviceInfo: 'Windows 11 / Chrome 128',
    status: 'Active Now',
    actionsLoggedCount: 18,
  },
  {
    id: 'LGN-9010',
    userName: 'Harish Gadipally',
    userEmail: 'harish.g@metaforgeit.com',
    userRole: 'lead',
    userAvatar: 'H',
    firstEverLoginTimestamp: 'Nov 10, 2025 at 08:15:00 AM',
    logDate: 'Today (Sep 09, 2026)',
    loginTime: '08:45:00 AM',
    logoutTime: 'Active Session (Logged in now)',
    sessionDuration: '5h 02m',
    activeScreenTime: '3h 45m',
    ipAddress: '192.168.1.10',
    deviceInfo: 'Windows 11 / Chrome 128',
    status: 'Active Now',
    actionsLoggedCount: 24,
  },
]
