import { INITIAL_RECRUITERS_PERMISSIONS_A } from './recruiters.partA'
import { INITIAL_RECRUITERS_PERMISSIONS_B } from './recruiters.partB'

export const INITIAL_RECRUITERS_PERMISSIONS = [
  ...INITIAL_RECRUITERS_PERMISSIONS_A,
  ...INITIAL_RECRUITERS_PERMISSIONS_B,
]
