import { RecruiterUserPermissionData } from './types'

export const INITIAL_RECRUITERS_PERMISSIONS_A: RecruiterUserPermissionData[] = [
  {
    id: 'user-1',
    name: 'Harish Gadipally',
    email: 'h.gadipally@talentflow.io',
    roleName: 'Team Lead',
    roleCode: 'lead',
    team: 'Engineering Pod',
    avatar: 'H',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: true,
      deleteRecords: false,
      reassignRequirements: true,
    },
  },
  {
    id: 'user-2',
    name: 'Marcus Chen',
    email: 'm.chen@talentflow.io',
    roleName: 'Senior Technical Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Pod',
    avatar: 'M',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-3',
    name: 'Priya Sharma',
    email: 'p.sharma@talentflow.io',
    roleName: 'IT Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Pod',
    avatar: 'P',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-4',
    name: 'Suresh Kulkarni',
    email: 's.kulkarni@talentflow.io',
    roleName: 'ERP Technical Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Pod',
    avatar: 'S',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-5',
    name: 'Adirala Sathvika',
    email: 'a.sathvika@talentflow.io',
    roleName: 'Junior Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Pod',
    avatar: 'A',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-6',
    name: 'Arvind GR',
    email: 'a.gr@talentflow.io',
    roleName: 'Sourcing Specialist',
    roleCode: 'recruiter',
    team: 'Engineering Pod',
    avatar: 'A',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
]
