import { RecruiterUserPermissionData } from './types'

export const INITIAL_RECRUITERS_PERMISSIONS_B: RecruiterUserPermissionData[] = [
  {
    id: 'user-7',
    name: 'Tom Walsh',
    email: 't.walsh@talentflow.io',
    roleName: 'Team Lead',
    roleCode: 'lead',
    team: 'Enterprise Accounts Pod',
    avatar: 'T',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: true,
      viewTeamAnalytics: true,
      deleteRecords: false,
      reassignRequirements: true,
    },
  },
  {
    id: 'user-8',
    name: 'Lakshmi V',
    email: 'l.v@talentflow.io',
    roleName: 'Lead Technical Recruiter',
    roleCode: 'lead',
    team: 'Enterprise Accounts Pod',
    avatar: 'L',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: true,
      viewTeamAnalytics: true,
      deleteRecords: false,
      reassignRequirements: true,
    },
  },
  {
    id: 'user-9',
    name: 'Sarah Kim',
    email: 's.kim@talentflow.io',
    roleName: 'FinTech Technical Recruiter',
    roleCode: 'recruiter',
    team: 'Enterprise Accounts Pod',
    avatar: 'S',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-10',
    name: 'Rahul Verma',
    email: 'r.verma@talentflow.io',
    roleName: 'Team Lead',
    roleCode: 'lead',
    team: 'Cloud & ERP Pod',
    avatar: 'R',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: true,
      viewTeamAnalytics: true,
      deleteRecords: false,
      reassignRequirements: true,
    },
  },
  {
    id: 'user-11',
    name: 'Neha Gupta',
    email: 'n.gupta@talentflow.io',
    roleName: 'SAP & Cloud Specialist',
    roleCode: 'recruiter',
    team: 'Cloud & ERP Pod',
    avatar: 'N',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-12',
    name: 'David Park',
    email: 'd.park@talentflow.io',
    roleName: 'Admin',
    roleCode: 'admin',
    team: 'Operations',
    avatar: 'D',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: true,
      viewTeamAnalytics: true,
      deleteRecords: true,
      reassignRequirements: true,
    },
  },
]
