import { RecruiterUserPermissionData } from './types'

export const INITIAL_RECRUITERS_PERMISSIONS: RecruiterUserPermissionData[] = [
  {
    id: 'user-1',
    name: 'Harish Gadipally',
    email: 'harish.g@metaforgeit.com',
    roleName: 'Team Lead',
    roleCode: 'lead',
    team: 'Engineering Pod',
    avatar: 'H',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: true,
      deleteRecords: false,
      reassignRequirements: true,
    },
  },
  {
    id: 'user-2',
    name: 'Arvind GR',
    email: 'arvind.gr@metaforgeit.com',
    roleName: 'Senior Technical Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Pod',
    avatar: 'A',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-3',
    name: 'Charlie Darwin',
    email: 'charlie.d@metaforgeit.com',
    roleName: 'Team Lead',
    roleCode: 'lead',
    team: 'Automotive Pod',
    avatar: 'C',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: true,
      viewTeamAnalytics: true,
      deleteRecords: false,
      reassignRequirements: true,
    },
  },
  {
    id: 'user-4',
    name: 'Harini Sindey',
    email: 'harini.s@metaforgeit.com',
    roleName: 'ERP Technical Recruiter',
    roleCode: 'recruiter',
    team: 'ERP & SAP Pod',
    avatar: 'H',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-5',
    name: 'Puttapaka Saiteja',
    email: 'saiteja.p@metaforgeit.com',
    roleName: 'Junior Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Pod',
    avatar: 'P',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: false,
      viewTeamAnalytics: false,
      deleteRecords: false,
      reassignRequirements: false,
    },
  },
  {
    id: 'user-6',
    name: 'Sarah Kim',
    email: 'sarah.k@metaforgeit.com',
    roleName: 'Admin',
    roleCode: 'admin',
    team: 'Executive Operations',
    avatar: 'S',
    status: 'Active',
    permissions: {
      addCandidates: true,
      submitToClients: true,
      scheduleInterviews: true,
      exportReportsCsv: true,
      viewTeamAnalytics: true,
      deleteRecords: true,
      reassignRequirements: true,
    },
  },
]
