import { UserAccountData } from './types'

export const INITIAL_USERS: UserAccountData[] = [
  {
    id: 'usr-101',
    name: 'Harish Gadipally',
    email: 'harish.g@metaforgeit.com',
    phone: '+91 98765 12345',
    employeeId: 'EMP-2024-001',
    role: 'Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Team',
    supervisor: 'Charlie Darwin (Lead)',
    assignedClient: 'Accenture',
    status: 'Active',
    twoFactorEnabled: true,
    lastLogin: 'Today • 09:30 AM',
    lastPasswordChange: '15 Jul 2026',
  },
  {
    id: 'usr-102',
    name: 'Arvind GR',
    email: 'arvind.gr@metaforgeit.com',
    phone: '+91 98123 45678',
    employeeId: 'EMP-2024-002',
    role: 'Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Team',
    supervisor: 'Charlie Darwin (Lead)',
    assignedClient: 'Accenture',
    status: 'Active',
    twoFactorEnabled: false,
    lastLogin: 'Today • 10:15 AM',
    lastPasswordChange: '01 Jun 2026',
  },
  {
    id: 'usr-103',
    name: 'Charlie Darwin',
    email: 'charlie.d@metaforgeit.com',
    phone: '+91 97654 32109',
    employeeId: 'EMP-2023-014',
    role: 'Team Lead',
    roleCode: 'lead',
    team: 'Automotive Team',
    supervisor: 'Super Admin Governance',
    assignedClient: 'Deloitte',
    status: 'Active',
    twoFactorEnabled: true,
    lastLogin: 'Today • 08:45 AM',
    lastPasswordChange: '10 Aug 2026',
  },
  {
    id: 'usr-104',
    name: 'Harini Sindey',
    email: 'harini.s@metaforgeit.com',
    phone: '+91 99887 76655',
    employeeId: 'EMP-2024-009',
    role: 'Recruiter',
    roleCode: 'recruiter',
    team: 'ERP & SAP Team',
    supervisor: 'Charlie Darwin (Lead)',
    assignedClient: 'Google',
    status: 'Active',
    twoFactorEnabled: true,
    lastLogin: 'Yesterday • 04:20 PM',
    lastPasswordChange: '20 May 2026',
  },
  {
    id: 'usr-105',
    name: 'Puttapaka Saiteja',
    email: 'saiteja.p@metaforgeit.com',
    phone: '+91 91234 56789',
    employeeId: 'EMP-2024-012',
    role: 'Recruiter',
    roleCode: 'recruiter',
    team: 'Engineering Team',
    supervisor: 'Charlie Darwin (Lead)',
    assignedClient: 'MetaForge',
    status: 'Active',
    twoFactorEnabled: false,
    lastLogin: 'Today • 11:05 AM',
    lastPasswordChange: '12 Apr 2026',
  },
  {
    id: 'usr-106',
    name: 'Sarah Kim',
    email: 'sarah.k@metaforgeit.com',
    phone: '+91 95555 44433',
    employeeId: 'EMP-2022-003',
    role: 'Admin',
    roleCode: 'admin',
    team: 'Executive Operations',
    supervisor: 'Super Admin Governance',
    assignedClient: 'All Clients',
    status: 'Active',
    twoFactorEnabled: true,
    lastLogin: 'Today • 08:00 AM',
    lastPasswordChange: '05 Aug 2026',
  },
]
