import { ClientPerformanceData } from '../ClientDetailAnalyticsPage'

export const CLIENT_PERFORMANCE_LIST: ClientPerformanceData[] = [
    {
      id: 'cli-1',
      clientName: 'METAFORGE (INTERNAL)',
      reqSent: 49,
      reqAssigned: 3,
      submissions: 6,
      subRatio: 0.12,
      openReqs: 49,
      closedReqs: 0,
      activeRecruiters: 2,
      requirementsList: [
        { id: 'REQ-M01', title: 'Internal Operations Associate', assignedRecruiter: 'lakshmi.v Recruiter', submissions: 4, status: 'In Progress', createdDate: '01 Aug 2026' },
        { id: 'REQ-M02', title: 'Talent Acquisition Coordinator', assignedRecruiter: 'Suresh kulkarni', submissions: 2, status: 'Open', createdDate: '05 Aug 2026' },
      ],
    },
    {
      id: 'cli-2',
      clientName: 'OTHER',
      reqSent: 104,
      reqAssigned: 6,
      submissions: 7,
      subRatio: 0.07,
      openReqs: 104,
      closedReqs: 0,
      activeRecruiters: 3,
      requirementsList: [
        { id: 'REQ-O01', title: 'Generic Sourcing Request', assignedRecruiter: 'Harini Sindey', submissions: 4, status: 'Open', createdDate: '28 Jul 2026' },
        { id: 'REQ-O02', title: 'Technical Consultant', assignedRecruiter: 'rahimoon Shaik', submissions: 3, status: 'In Progress', createdDate: '02 Aug 2026' },
      ],
    },
    {
      id: 'cli-3',
      clientName: 'OTHER COMPANY / SOURCE',
      reqSent: 31,
      reqAssigned: 1,
      submissions: 1,
      subRatio: 0.03,
      openReqs: 31,
      closedReqs: 0,
      activeRecruiters: 1,
      requirementsList: [
        { id: 'REQ-OCS01', title: 'External Partner Developer', assignedRecruiter: 'Charlie Darwin', submissions: 1, status: 'Open', createdDate: '04 Aug 2026' },
      ],
    },
    {
      id: 'cli-4',
      clientName: 'LTTS',
      reqSent: 204,
      reqAssigned: 105,
      submissions: 291,
      subRatio: 1.43,
      openReqs: 203,
      closedReqs: 1,
      activeRecruiters: 6,
      requirementsList: [
        { id: 'REQ-L01', title: 'Senior Java Full Stack Lead', assignedRecruiter: 'Harish Gadipally', submissions: 42, status: 'Closed', createdDate: '12 Jul 2026' },
        { id: 'REQ-L02', title: 'AUTOSAR Software Architect', assignedRecruiter: 'rahimoon Shaik', submissions: 22, status: 'In Progress', createdDate: '20 Jul 2026' },
        { id: 'REQ-L03', title: 'Catia V5 Mechanical Engineer', assignedRecruiter: 'Lingoji Pavani', submissions: 14, status: 'In Progress', createdDate: '01 Aug 2026' },
      ],
    },
    {
      id: 'cli-5',
      clientName: 'ITC',
      reqSent: 69,
      reqAssigned: 21,
      submissions: 28,
      subRatio: 0.41,
      openReqs: 69,
      closedReqs: 0,
      activeRecruiters: 3,
      requirementsList: [
        { id: 'REQ-I01', title: 'SAP MM Functional Lead', assignedRecruiter: 'Suresh kulkarni', submissions: 18, status: 'In Progress', createdDate: '25 Jul 2026' },
        { id: 'REQ-I02', title: 'FICO Module Consultant', assignedRecruiter: 'Lingoji Pavani', submissions: 10, status: 'Open', createdDate: '03 Aug 2026' },
      ],
    },
    {
      id: 'cli-6',
      clientName: 'KPMG',
      reqSent: 41,
      reqAssigned: 9,
      submissions: 10,
      subRatio: 0.24,
      openReqs: 41,
      closedReqs: 0,
      activeRecruiters: 2,
      requirementsList: [
        { id: 'REQ-K01', title: 'Cyber Risk Advisory Lead', assignedRecruiter: 'Arvind GR', submissions: 6, status: 'In Progress', createdDate: '30 Jul 2026' },
        { id: 'REQ-K02', title: 'Financial Audit Analyst', assignedRecruiter: 'Harini Sindey', submissions: 4, status: 'Open', createdDate: '06 Aug 2026' },
      ],
    },
    {
      id: 'cli-7',
      clientName: 'DELOITTE',
      reqSent: 1,
      reqAssigned: 1,
      submissions: 3,
      subRatio: 3.00,
      openReqs: 1,
      closedReqs: 0,
      activeRecruiters: 1,
      requirementsList: [
        { id: 'REQ-D01', title: 'Cloud Transformation Manager', assignedRecruiter: 'lakshmi.v Recruiter', submissions: 3, status: 'In Progress', createdDate: '02 Aug 2026' },
      ],
    },
    {
      id: 'cli-8',
      clientName: 'METAFORGE',
      reqSent: 1,
      reqAssigned: 1,
      submissions: 4,
      subRatio: 4.00,
      openReqs: 1,
      closedReqs: 0,
      activeRecruiters: 1,
      requirementsList: [
        { id: 'REQ-MF01', title: 'Core Engine Platform Architect', assignedRecruiter: 'Harish Gadipally', submissions: 4, status: 'In Progress', createdDate: '07 Aug 2026' },
      ],
    },
]
