import { RecruiterReqDashboardItem } from './types'

export const RECRUITER_REQ_SUBMISSION_DASHBOARD_DATA_PART1: RecruiterReqDashboardItem[] = [
  {
    id: 'dash-01',
    recruiterName: 'Harish Gadipally',
    recruiterRole: 'Team Lead / Senior Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-2026-08-12-001',
    jobTitle: 'TPC - Requirement - C# Automation - Embedded',
    positions: 5,
    clientName: 'LTTS / L&T',
    submissionsCount: 14,
    timestamp: '21 Aug 2026, 10:15 AM',
    receivedTime: '12 Aug 2026, 05:30 AM',
    firstSubmissionTime: '12 Aug 2026, 09:30 AM',
    tat: '4h 00m',
    status: 'In Progress',
  },
  {
    id: 'dash-02',
    recruiterName: 'Harish Gadipally',
    recruiterRole: 'Team Lead / Senior Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-2026-08-12-003',
    jobTitle: 'Senior React / Fullstack Architect',
    positions: 3,
    clientName: 'Accenture Enterprise',
    submissionsCount: 18,
    timestamp: '20 Aug 2026, 04:45 PM',
    receivedTime: '13 Aug 2026, 08:00 AM',
    firstSubmissionTime: '13 Aug 2026, 11:15 AM',
    tat: '3h 15m',
    status: 'Target Achieved',
  },
  {
    id: 'dash-03',
    recruiterName: 'Marcus Chen',
    recruiterRole: 'Senior Technical Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-701',
    jobTitle: 'Lead Java Full Stack Developer',
    positions: 8,
    clientName: 'Accenture Enterprise',
    submissionsCount: 24,
    timestamp: '21 Aug 2026, 09:50 AM',
    receivedTime: '10 Aug 2026, 07:00 AM',
    firstSubmissionTime: '10 Aug 2026, 10:00 AM',
    tat: '3h 00m',
    status: 'In Progress',
  },
  {
    id: 'dash-04',
    recruiterName: 'Marcus Chen',
    recruiterRole: 'Senior Technical Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-702',
    jobTitle: 'Senior React Native Mobile Dev',
    positions: 4,
    clientName: 'Accenture Enterprise',
    submissionsCount: 24,
    timestamp: '19 Aug 2026, 03:20 PM',
    receivedTime: '11 Aug 2026, 09:15 AM',
    firstSubmissionTime: '11 Aug 2026, 02:45 PM',
    tat: '5h 30m',
    status: 'Target Achieved',
  },
  {
    id: 'dash-05',
    recruiterName: 'Priya Sharma',
    recruiterRole: 'IT Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-2026-08-06-005',
    jobTitle: 'Java Cloud Architect',
    positions: 6,
    clientName: 'Goldman Sachs',
    submissionsCount: 18,
    timestamp: '20 Aug 2026, 06:10 PM',
    receivedTime: '07 Aug 2026, 09:00 AM',
    firstSubmissionTime: '07 Aug 2026, 01:20 PM',
    tat: '4h 20m',
    status: 'In Progress',
  },
  {
    id: 'dash-06',
    recruiterName: 'Lakshmi V',
    recruiterRole: 'Lead Technical Recruiter',
    teamLead: 'Tom Walsh',
    reqId: 'REQ-2026-08-07-006',
    jobTitle: 'Automotive Embedded Systems Engineer',
    positions: 10,
    clientName: 'Tesla Mobility',
    submissionsCount: 22,
    timestamp: '21 Aug 2026, 08:30 AM',
    receivedTime: '08 Aug 2026, 08:30 AM',
    firstSubmissionTime: '08 Aug 2026, 10:45 AM',
    tat: '2h 15m',
    status: 'In Progress',
  },
  {
    id: 'dash-07',
    recruiterName: 'Suresh Kulkarni',
    recruiterRole: 'ERP Technical Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-2026-08-12-004',
    jobTitle: 'PLM / PDM Lead Engineer',
    positions: 4,
    clientName: 'Accenture',
    submissionsCount: 18,
    timestamp: '19 Aug 2026, 05:00 PM',
    receivedTime: '14 Aug 2026, 06:45 AM',
    firstSubmissionTime: '14 Aug 2026, 12:00 PM',
    tat: '5h 15m',
    status: 'In Progress',
  },
  {
    id: 'dash-08',
    recruiterName: 'Lingoji Pavani',
    recruiterRole: 'Technical Sourcing Lead',
    teamLead: 'Tom Walsh',
    reqId: 'REQ-2026-06-08-001',
    jobTitle: '.NET Core Backend Architect',
    positions: 2,
    clientName: 'LTTS Mobility',
    submissionsCount: 12,
    timestamp: '18 Aug 2026, 02:15 PM',
    receivedTime: '09 Aug 2026, 08:00 AM',
    firstSubmissionTime: '09 Aug 2026, 11:30 AM',
    tat: '3h 30m',
    status: 'Submissions Completed',
  },
]
