import { RecruiterReqDashboardItem } from './types'

export const RECRUITER_REQ_SUBMISSION_DASHBOARD_DATA_PART2: RecruiterReqDashboardItem[] = [
  {
    id: 'dash-09',
    recruiterName: 'rahimoon Shaik',
    recruiterRole: 'Automotive Sourcing Specialist',
    teamLead: 'Tom Walsh',
    reqId: 'REQ-2026-08-07-007',
    jobTitle: 'BIW Sheet Metal Product Design Lead',
    positions: 5,
    clientName: 'Continental Automotive',
    submissionsCount: 15,
    timestamp: '20 Aug 2026, 01:40 PM',
    receivedTime: '10 Aug 2026, 11:00 AM',
    firstSubmissionTime: '10 Aug 2026, 04:10 PM',
    tat: '5h 10m',
    status: 'In Progress',
  },
  {
    id: 'dash-10',
    recruiterName: 'Harini Sindey',
    recruiterRole: 'Enterprise Systems Specialist',
    teamLead: 'Tom Walsh',
    reqId: 'REQ-2026-07-20-009',
    jobTitle: 'SAP MM + Ariba Functional Lead',
    positions: 3,
    clientName: 'ITC Infotech',
    submissionsCount: 18,
    timestamp: '21 Aug 2026, 09:15 AM',
    receivedTime: '21 Jul 2026, 07:30 AM',
    firstSubmissionTime: '21 Jul 2026, 10:00 AM',
    tat: '2h 30m',
    status: 'Target Achieved',
  },
  {
    id: 'dash-11',
    recruiterName: 'Marcus Chen',
    recruiterRole: 'Senior Technical Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-2026-08-04-002',
    jobTitle: 'DevOps / Kubernetes Cloud Engineer',
    positions: 5,
    clientName: 'Goldman Sachs',
    submissionsCount: 16,
    timestamp: '21 Aug 2026, 11:30 AM',
    receivedTime: '05 Aug 2026, 10:00 AM',
    firstSubmissionTime: '05 Aug 2026, 02:15 PM',
    tat: '4h 15m',
    status: 'In Progress',
  },
  {
    id: 'dash-12',
    recruiterName: 'Marcus Chen',
    recruiterRole: 'Senior Technical Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-2026-08-01-010',
    jobTitle: 'Cybersecurity Threat Analyst',
    positions: 2,
    clientName: 'Tesla Mobility',
    submissionsCount: 9,
    timestamp: '18 Aug 2026, 05:10 PM',
    receivedTime: '02 Aug 2026, 07:00 AM',
    firstSubmissionTime: '02 Aug 2026, 09:00 AM',
    tat: '2h 00m',
    status: 'Submissions Completed',
  },
  {
    id: 'dash-13',
    recruiterName: 'Marcus Chen',
    recruiterRole: 'Senior Technical Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-703',
    jobTitle: 'Senior Staff AI / ML Engineer',
    positions: 4,
    clientName: 'Accenture Enterprise',
    submissionsCount: 15,
    timestamp: '20 Aug 2026, 03:45 PM',
    receivedTime: '15 Aug 2026, 08:30 AM',
    firstSubmissionTime: '15 Aug 2026, 10:30 AM',
    tat: '2h 00m',
    status: 'In Progress',
  },
  {
    id: 'dash-14',
    recruiterName: 'Marcus Chen',
    recruiterRole: 'Senior Technical Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-704',
    jobTitle: 'Principal Distributed Systems Engineer',
    positions: 3,
    clientName: 'Goldman Sachs',
    submissionsCount: 12,
    timestamp: '15 Aug 2026, 11:20 AM',
    receivedTime: '10 Aug 2026, 06:00 AM',
    firstSubmissionTime: '10 Aug 2026, 09:15 AM',
    tat: '3h 15m',
    status: 'Target Achieved',
  },
  {
    id: 'dash-15',
    recruiterName: 'Marcus Chen',
    recruiterRole: 'Senior Technical Recruiter',
    teamLead: 'Harish Gadipally',
    reqId: 'REQ-705',
    jobTitle: 'Lead Data Platform Architect',
    positions: 6,
    clientName: 'Tesla Mobility',
    submissionsCount: 20,
    timestamp: '25 Jul 2026, 04:00 PM',
    receivedTime: '20 Jul 2026, 08:00 AM',
    firstSubmissionTime: '20 Jul 2026, 11:00 AM',
    tat: '3h 00m',
    status: 'Submissions Completed',
  },
]
