import { RecruiterDetailData } from '../RecruiterDetailAnalyticsPage'

export const RECRUITERS_PERFORMANCE_LIST_PART1: RecruiterDetailData[] = [
    {
      id: 'rec-lead-0',
      name: 'Harish Gadipally',
      role: 'Team Lead',
      teamLead: 'Harish Gadipally',
      primaryClient: 'Accenture',
      team: 'Engineering Pod',
      avatar: 'H',
      requirementsCount: 45,
      workedReqs: 38,
      nonWorkedReqs: 7,
      submissionsCount: 142,
      shortlistedCount: 48,
      noSubmissionsCount: 12,
      interviewsCount: 36,
      hiresCount: 11,
      conversionRate: '22.9%',
      dailyTaskStatus: 'Done (5/5)',
      weeklyProgress: '22 / 25',
      weeklyProgressPct: 88,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-701', title: 'Lead Java Full Stack Developer', client: 'Accenture', status: 'Worked', submissions: 42, interviews: 12 },
        { id: 'REQ-702', title: 'Senior React Native Mobile Dev', client: 'LTTS Automotive', status: 'Worked', submissions: 36, interviews: 10 },
        { id: 'REQ-703', title: 'Cloud Solutions Architect', client: 'Infosys', status: 'Worked', submissions: 28, interviews: 8 },
        { id: 'REQ-704', title: 'Cyber Security Analyst', client: 'HCL Technologies', status: 'Non-Worked', submissions: 0, interviews: 0 },
      ],
    },
    {
      id: 'rec-m1',
      name: 'Marcus Chen',
      role: 'Senior Technical Recruiter',
      teamLead: 'Harish Gadipally',
      primaryClient: 'Accenture',
      team: 'Engineering Pod',
      avatar: 'M',
      requirementsCount: 14,
      workedReqs: 12,
      nonWorkedReqs: 2,
      submissionsCount: 48,
      shortlistedCount: 18,
      noSubmissionsCount: 3,
      interviewsCount: 12,
      hiresCount: 4,
      conversionRate: '25.0%',
      dailyTaskStatus: 'Done (5/5)',
      weeklyProgress: '20 / 25',
      weeklyProgressPct: 80,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-701', title: 'Lead Java Full Stack Developer', client: 'Accenture', status: 'Worked', submissions: 24, interviews: 8 },
        { id: 'REQ-702', title: 'Senior React Native Mobile Dev', client: 'Accenture', status: 'Worked', submissions: 24, interviews: 4 },
      ],
    },
    {
      id: 'rec-p1',
      name: 'Priya Sharma',
      role: 'IT Recruiter',
      teamLead: 'Harish Gadipally',
      primaryClient: 'Accenture',
      team: 'Engineering Pod',
      avatar: 'P',
      requirementsCount: 12,
      workedReqs: 10,
      nonWorkedReqs: 2,
      submissionsCount: 36,
      shortlistedCount: 14,
      noSubmissionsCount: 2,
      interviewsCount: 9,
      hiresCount: 3,
      conversionRate: '21.4%',
      dailyTaskStatus: 'Done (4/5)',
      weeklyProgress: '18 / 25',
      weeklyProgressPct: 72,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-701', title: 'Lead Java Full Stack Developer', client: 'Accenture', status: 'Worked', submissions: 18, interviews: 5 },
        { id: 'REQ-703', title: 'Cloud Solutions Architect', client: 'Accenture', status: 'Worked', submissions: 18, interviews: 4 },
      ],
    },
    {
      id: 'rec-4',
      name: 'Suresh Kulkarni',
      role: 'ERP Technical Recruiter',
      teamLead: 'Harish Gadipally',
      primaryClient: 'Accenture',
      team: 'Engineering Pod',
      avatar: 'S',
      requirementsCount: 27,
      workedReqs: 19,
      nonWorkedReqs: 8,
      submissionsCount: 46,
      shortlistedCount: 16,
      noSubmissionsCount: 9,
      interviewsCount: 5,
      hiresCount: 4,
      conversionRate: '18.5%',
      dailyTaskStatus: 'In progress (2/5) - 3 to go',
      weeklyProgress: '12 / 25',
      weeklyProgressPct: 48,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-401', title: 'PLM / PDM Engineer', client: 'Accenture', status: 'Worked', submissions: 18, interviews: 3 },
        { id: 'REQ-402', title: 'Change Management Specialist', client: 'Accenture', status: 'Worked', submissions: 14, interviews: 2 },
      ],
    },
    {
      id: 'rec-5',
      name: 'Adirala Sathvika',
      role: 'Junior Recruiter',
      teamLead: 'Harish Gadipally',
      primaryClient: 'Wipro',
      team: 'Engineering Pod',
      avatar: 'A',
      requirementsCount: 1,
      workedReqs: 0,
      nonWorkedReqs: 1,
      submissionsCount: 0,
      shortlistedCount: 0,
      noSubmissionsCount: 1,
      interviewsCount: 0,
      hiresCount: 0,
      conversionRate: '0%',
      dailyTaskStatus: 'In progress (0/5) - 5 to go',
      weeklyProgress: '0 / 25',
      weeklyProgressPct: 0,
      status: 'Critical',
      requirementsList: [
        { id: 'REQ-501', title: 'Junior QA Automation Tester', client: 'Wipro', status: 'Non-Worked', submissions: 0, interviews: 0, reasonNote: 'Location constraint / No local candidates available' },
      ],
    },
    {
      id: 'rec-6',
      name: 'Arvind GR',
      role: 'Sourcing Specialist',
      teamLead: 'Harish Gadipally',
      primaryClient: 'Infosys',
      team: 'Engineering Pod',
      avatar: 'A',
      requirementsCount: 4,
      workedReqs: 3,
      nonWorkedReqs: 1,
      submissionsCount: 12,
      shortlistedCount: 4,
      noSubmissionsCount: 1,
      interviewsCount: 3,
      hiresCount: 1,
      conversionRate: '15.0%',
      dailyTaskStatus: 'Done (3/5)',
      weeklyProgress: '12 / 25',
      weeklyProgressPct: 48,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-601', title: 'Frontend Developer', client: 'Infosys', status: 'Worked', submissions: 12, interviews: 3 },
      ],
    },
]
