import { RecruiterDetailData } from '../RecruiterDetailAnalyticsPage'

export const RECRUITERS_PERFORMANCE_LIST_PART2: RecruiterDetailData[] = [
    {
      id: 'rec-lead-2',
      name: 'Tom Walsh',
      role: 'Team Lead',
      teamLead: 'Tom Walsh',
      primaryClient: 'Goldman Sachs',
      team: 'Enterprise Accounts Pod',
      avatar: 'T',
      requirementsCount: 52,
      workedReqs: 44,
      nonWorkedReqs: 8,
      submissionsCount: 168,
      shortlistedCount: 62,
      noSubmissionsCount: 10,
      interviewsCount: 24,
      hiresCount: 9,
      conversionRate: '28.4%',
      dailyTaskStatus: 'Done (5/5)',
      weeklyProgress: '24 / 25',
      weeklyProgressPct: 96,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-TW01', title: 'Principal Financial Architect', client: 'Goldman Sachs', status: 'Worked', submissions: 32, interviews: 8 },
        { id: 'REQ-TW02', title: 'Lead Quantitative Developer', client: 'JPMorgan Chase', status: 'Worked', submissions: 28, interviews: 6 },
      ],
    },
    {
      id: 'rec-1',
      name: 'Lakshmi V',
      role: 'Lead Technical Recruiter',
      teamLead: 'Tom Walsh',
      primaryClient: 'Goldman Sachs',
      team: 'Enterprise Accounts Pod',
      avatar: 'L',
      requirementsCount: 72,
      workedReqs: 58,
      nonWorkedReqs: 14,
      submissionsCount: 194,
      shortlistedCount: 84,
      noSubmissionsCount: 32,
      interviewsCount: 22,
      hiresCount: 12,
      conversionRate: '26.2%',
      dailyTaskStatus: 'Done (5/5)',
      weeklyProgress: '21 / 25',
      weeklyProgressPct: 84,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-101', title: 'Senior Java Full Stack Engineer', client: 'Goldman Sachs', status: 'Worked', submissions: 24, interviews: 8 },
        { id: 'REQ-102', title: 'React.js Frontend Architect', client: 'Goldman Sachs', status: 'Worked', submissions: 18, interviews: 5 },
      ],
    },
    {
      id: 'rec-t1',
      name: 'Sarah Kim',
      role: 'FinTech Technical Recruiter',
      teamLead: 'Tom Walsh',
      primaryClient: 'JPMorgan Chase',
      team: 'Enterprise Accounts Pod',
      avatar: 'S',
      requirementsCount: 18,
      workedReqs: 15,
      nonWorkedReqs: 3,
      submissionsCount: 54,
      shortlistedCount: 22,
      noSubmissionsCount: 4,
      interviewsCount: 14,
      hiresCount: 5,
      conversionRate: '27.7%',
      dailyTaskStatus: 'Done (5/5)',
      weeklyProgress: '22 / 25',
      weeklyProgressPct: 88,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-SK01', title: 'Risk Systems Developer', client: 'JPMorgan Chase', status: 'Worked', submissions: 30, interviews: 8 },
      ],
    },

    // =========================================================================
    // 👑 TEAM 3: RAHUL VERMA (TEAM LEAD) & HIS TEAM MEMBERS
    // =========================================================================
    {
      id: 'rec-lead-3',
      name: 'Rahul Verma',
      role: 'Team Lead',
      teamLead: 'Rahul Verma',
      primaryClient: 'Morgan Stanley',
      team: 'Cloud & ERP Pod',
      avatar: 'R',
      requirementsCount: 38,
      workedReqs: 32,
      nonWorkedReqs: 6,
      submissionsCount: 110,
      shortlistedCount: 42,
      noSubmissionsCount: 8,
      interviewsCount: 18,
      hiresCount: 7,
      conversionRate: '24.1%',
      dailyTaskStatus: 'Done (5/5)',
      weeklyProgress: '20 / 25',
      weeklyProgressPct: 80,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-RV01', title: 'Cloud Infrastructure Director', client: 'Morgan Stanley', status: 'Worked', submissions: 28, interviews: 6 },
      ],
    },
    {
      id: 'rec-r1',
      name: 'Neha Gupta',
      role: 'SAP & Cloud Specialist',
      teamLead: 'Rahul Verma',
      primaryClient: 'Morgan Stanley',
      team: 'Cloud & ERP Pod',
      avatar: 'N',
      requirementsCount: 16,
      workedReqs: 14,
      nonWorkedReqs: 2,
      submissionsCount: 42,
      shortlistedCount: 18,
      noSubmissionsCount: 3,
      interviewsCount: 10,
      hiresCount: 4,
      conversionRate: '23.8%',
      dailyTaskStatus: 'Done (4/5)',
      weeklyProgress: '19 / 25',
      weeklyProgressPct: 76,
      status: 'On Track',
      requirementsList: [
        { id: 'REQ-NG01', title: 'SAP HANA Lead Consultant', client: 'Morgan Stanley', status: 'Worked', submissions: 22, interviews: 5 },
      ],
    },
]
