import { OfferLetterRowItem } from './types'

export const DEFAULT_OFFER_LETTERS: OfferLetterRowItem[] = [
  {
    id: 'off-1',
    candidateName: 'Pritish Malik',
    position: 'C# Automation - Bangalore/Mysore',
    client: 'LTTS / L&T',
    requirementId: 'REQ-003',
    offerDate: 'Aug 19, 2026',
    offeredCTC: '₹22,00,000 PA',
    joiningDate: 'Sep 01, 2026',
    status: 'Offer Released',
    submittedBy: 'Marcus Chen',
  },
  {
    id: 'off-2',
    candidateName: 'Vidyasagar Gade',
    position: 'Cloud Solutions Architect',
    client: 'Accenture',
    requirementId: 'REQ-2026-08-12-003',
    offerDate: 'Aug 18, 2026',
    offeredCTC: '₹34,00,000 PA',
    joiningDate: 'Sep 15, 2026',
    status: 'Accepted',
    submittedBy: 'Harish Gadipally',
  },
  {
    id: 'off-3',
    candidateName: 'Arpit Srivastav',
    position: 'Senior React Native Dev',
    client: 'Accenture',
    requirementId: 'REQ-2026-08-12-002',
    offerDate: 'Aug 15, 2026',
    offeredCTC: '₹26,00,000 PA',
    joiningDate: 'Aug 25, 2026',
    status: 'Joined',
    submittedBy: 'Priya Sharma',
  },
  {
    id: 'off-4',
    candidateName: 'Kanchan Meshram',
    position: 'AI Solutions Specialist',
    client: 'Continental Automotive',
    requirementId: 'REQ-2026-08-12-006',
    offerDate: 'Aug 12, 2026',
    offeredCTC: '₹28,00,000 PA',
    status: 'Not Joined',
    notJoinedReason: 'Competing offer with higher compensation',
    notJoinedNote: 'Candidate accepted competing offer from Microsoft with ₹34 LPA CTC (20% higher than approved client CTC).',
    notJoinedDate: 'Aug 22, 2026',
    submittedBy: 'Marcus Chen',
  },
  {
    id: 'off-5',
    candidateName: 'Rohan Patil',
    position: 'Java Lead Architect',
    client: 'Goldman Sachs',
    requirementId: 'REQ-2026-08-06-005',
    offerDate: 'Aug 10, 2026',
    offeredCTC: '₹36,00,000 PA',
    status: 'Not Joined',
    notJoinedReason: 'Counter offer from current employer',
    notJoinedNote: 'Employer promoted candidate to Technical Director with retention bonus and matching CTC; candidate withdrew joining commitment.',
    notJoinedDate: 'Aug 20, 2026',
    submittedBy: 'Lingoji Pavani',
  },
  {
    id: 'off-6',
    candidateName: 'Meera Deshmukh',
    position: 'DevOps & Kubernetes Lead',
    client: 'Deloitte',
    requirementId: 'REQ-2026-08-07-009',
    offerDate: 'Aug 05, 2026',
    offeredCTC: '₹30,00,000 PA',
    joiningDate: 'Aug 18, 2026',
    status: 'Joined',
    submittedBy: 'Harish Gadipally',
  },
]
