import { RejectedCandidateRowItem } from './types'

export const DEFAULT_REJECTED_CANDIDATES: RejectedCandidateRowItem[] = [
  {
    id: 'rej-0',
    candidateName: 'Kunal Saxena',
    candidateId: 'CAND-18015',
    position: 'Cloud DevOps Architect',
    company: 'Accenture',
    rejectedStage: 'L2 Technical',
    rejectionReason: 'System architecture design score below threshold',
    evaluatorNotes: 'Candidate had good cloud basics but struggled with Kubernetes cluster failover scenario.',
    evaluatedBy: 'Harish Gadipally (Lead)',
    submittedBy: 'Harish Gadipally',
    teamLead: 'Harish Gadipally',
    rejectionDate: 'Aug 17, 2026',
    requirementId: 'REQ-2026-08-12-001',
  },
  {
    id: 'rej-1',
    candidateName: 'Sandeep Patil',
    candidateId: 'CAND-18012',
    position: 'PLM / PDM Lead Engineer',
    company: 'Accenture',
    rejectedStage: 'L1 Technical',
    rejectionReason: 'Technical evaluation score below threshold (C++ & PLM architecture round)',
    evaluatorNotes: 'Failed coding assessment on C++ memory management and CAD API integrations.',
    evaluatedBy: 'Rajesh V. (Tech Panel L1)',
    submittedBy: 'Suresh kulkarni',
    teamLead: 'Harish Gadipally',
    rejectionDate: 'Aug 16, 2026',
    requirementId: 'REQ-2026-08-12-004',
  },
  {
    id: 'rej-2',
    candidateName: 'Abhijit Narke',
    candidateId: 'CAND-18009',
    position: 'Java Lead Engineer',
    company: 'Goldman Sachs',
    rejectedStage: 'Screening',
    rejectionReason: 'Notice period exceeds 60 days budget limit',
    evaluatorNotes: 'Candidate serving 90 days notice period; client requires immediate joiner within 30 days.',
    evaluatedBy: 'Harish Gadipally (Lead)',
    submittedBy: 'Lingoji Pavani',
    teamLead: 'Tom Walsh',
    rejectionDate: 'Aug 14, 2026',
    requirementId: 'REQ-2026-08-06-005',
  },
  {
    id: 'rej-3',
    candidateName: 'Ben Wallace',
    candidateId: 'CAND-18007',
    position: 'Python ML Specialist',
    company: 'Tesla',
    rejectedStage: 'L3 / Manager',
    rejectionReason: 'Salary expectation exceeds approved budget for Senior Band',
    evaluatorNotes: 'Expected CTC is ₹38 LPA vs approved client band max of ₹28 LPA.',
    evaluatedBy: 'Sarah Jenkins (Director of AI)',
    submittedBy: 'Adirala sathvika',
    teamLead: 'Nina Brooks',
    rejectionDate: 'Aug 13, 2026',
    requirementId: 'REQ-2026-08-07-007',
  },
  {
    id: 'rej-4',
    candidateName: 'Rahul Deshmukh',
    candidateId: 'CAND-18005',
    position: 'Senior React Developer',
    company: 'Accenture',
    rejectedStage: 'L2 Technical',
    rejectionReason: 'State management & SSR architecture design score insufficient',
    evaluatorNotes: 'Struggled with Next.js SSR hydration and Redux Toolkit state normalization live coding exercise.',
    evaluatedBy: 'Amitabh Sen (Lead Architect)',
    submittedBy: 'Marcus Chen',
    teamLead: 'Harish Gadipally',
    rejectionDate: 'Aug 11, 2026',
    requirementId: 'REQ-2026-08-12-001',
  },
  {
    id: 'rej-5',
    candidateName: 'Neha Kulkarni',
    candidateId: 'CAND-18003',
    position: 'DevOps Lead Engineer',
    company: 'JP Morgan',
    rejectedStage: 'Final HR Round',
    rejectionReason: 'Shift timing availability mismatch & competing offer conflict',
    evaluatorNotes: 'Unavailable for mandatory US shift rotation schedule.',
    evaluatedBy: 'Ananya Roy (HR Business Partner)',
    submittedBy: 'Priya Sharma',
    teamLead: 'Tom Walsh',
    rejectionDate: 'Aug 09, 2026',
    requirementId: 'REQ-2026-08-12-003',
  },
  {
    id: 'rej-6',
    candidateName: 'Vikramaditya Sen',
    candidateId: 'CAND-18001',
    position: 'Automotive Embedded Engineer',
    company: 'Continental Automotive',
    rejectedStage: 'Screening',
    rejectionReason: 'Mandatory Catia V6 door closure design certification missing',
    evaluatorNotes: 'Failed initial JD screening checklist for Catia V6 packaging skills.',
    evaluatedBy: 'Marcus Chen (Recruiter)',
    submittedBy: 'Marcus Chen',
    teamLead: 'Harish Gadipally',
    rejectionDate: 'Aug 08, 2026',
    requirementId: 'REQ-2026-08-07-006',
  },
]

