import { ScheduleRowItem } from './types'

export const DEFAULT_SCHEDULE_ROWS: ScheduleRowItem[] = [
  {
    id: '0',
    candidateName: 'Pradeep Kumar',
    position: 'Senior React / Fullstack Architect',
    company: 'Accenture',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Harish Gadipally',
    round: 'L1 Technical',
    dateTime: 'Today, 12:00 PM',
    mode: 'Online',
    status: 'In Progress',
    requirementId: 'REQ-2026-08-12-001',
  },
  {
    id: '1',
    candidateName: 'Arpit Srivastav',
    position: 'Senior React Native Mobile Dev',
    company: 'Accenture',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Marcus Chen',
    round: 'L2 Technical',
    dateTime: '2026-08-18 18:00',
    mode: 'Online',
    status: 'In Progress',
    requirementId: 'REQ-2026-08-12-002',
  },
  {
    id: '2',
    candidateName: 'Vidyasagar Gade',
    position: 'Cloud Solutions Architect',
    company: 'Accenture',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Priya Sharma',
    round: 'Final HR Round (All Rounds Completed)',
    dateTime: '2026-08-19 14:00',
    mode: 'Online',
    status: 'Completed',
    requirementId: 'REQ-2026-08-12-003',
  },
  {
    id: '3',
    candidateName: 'Siddharth Rao',
    position: 'PLM / PDM Lead Engineer',
    company: 'Accenture',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Suresh kulkarni',
    round: 'L1 Technical',
    dateTime: '2026-08-19 10:00',
    mode: 'Online',
    status: 'In Progress',
    requirementId: 'REQ-2026-08-12-004',
  },
  {
    id: '4',
    candidateName: 'Alex Turner',
    position: 'Lead Java Engineer',
    company: 'Accenture',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Marcus Chen',
    round: 'Technical Round 1',
    dateTime: '2026-08-20 13:06',
    mode: 'Online',
    status: 'Upcoming',
    requirementId: 'REQ-2026-08-12-005',
  },
  {
    id: '5',
    candidateName: 'Kanchan Meshram',
    position: 'AI Solutions Specialist',
    company: 'Accenture',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Priya Sharma',
    round: 'Technical Round 2',
    dateTime: '2026-08-20 11:45',
    mode: 'Online',
    status: 'In Progress',
    requirementId: 'REQ-2026-08-12-006',
  },
  {
    id: '6',
    candidateName: 'Rania Khalil',
    position: 'Java Architect',
    company: 'Goldman Sachs',
    teamLead: 'Tom Walsh',
    submittedBy: 'lakshmi.v Recruiter',
    round: 'Manager Round',
    dateTime: 'Aug 06, 02:00 PM',
    mode: 'Online',
    status: 'In Progress',
    requirementId: 'REQ-2026-08-06-005',
  },
  {
    id: '7',
    candidateName: 'Ben Wallace',
    position: 'Python ML Engineer',
    company: 'Tesla',
    teamLead: 'Nina Brooks',
    submittedBy: 'Recruiter',
    round: 'Screening',
    dateTime: 'Aug 07, 11:00 AM',
    mode: 'Online',
    status: 'In Progress',
    requirementId: 'REQ-2026-08-07-006',
  },
  {
    id: '8',
    candidateName: 'Pritish Malik',
    position: 'C# Automation - Bangalore/Mysore',
    company: 'LTTS / L&T',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Harish Gadipally',
    round: 'L3 / Final Round (Offer Released)',
    dateTime: 'Today, 02:30 PM',
    mode: 'Online',
    status: 'Completed',
    requirementId: 'REQ-003',
  },
  {
    id: '9',
    candidateName: 'Ananya Deshmukh',
    position: 'Senior Data Scientist',
    company: 'Microsoft',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Harish Gadipally',
    round: 'Final HR Round (All Rounds Completed)',
    dateTime: 'Aug 21, 11:00 AM',
    mode: 'Online',
    status: 'Completed',
    requirementId: 'REQ-004',
  },
  {
    id: '10',
    candidateName: 'Rajesh Verma',
    position: 'Salesforce Admin',
    company: 'Deloitte',
    teamLead: 'Harish Gadipally',
    submittedBy: 'Harish Gadipally',
    round: 'L2 Technical Evaluation',
    dateTime: 'Aug 21, 03:00 PM',
    mode: 'Online',
    status: 'In Progress',
    requirementId: 'REQ-005',
  },
]
