import { CandidateRepoItem } from './types'

export const DEFAULT_REPO_CANDIDATES: CandidateRepoItem[] = [
  {
    id: '1',
    candidateId: '18016',
    name: 'Priyanka Sharma',
    email: 'priyanka.sharma@gmail.com',
    phone: '+91 98210 44905',
    technology: 'Test Manager / QA Lead',
    totalExperience: '11 Years 3 Months',
    relevantExperience: '9 Years',
    createdDate: '12 Aug 2026',
    createdBy: 'Nithya Maripelly',
    status: 'In Review',
    qualification: 'M.Tech Software Engineering, IIT Hyderabad',
    skills: 'Test Management, Automation Frameworks, Selenium, Appium, CI/CD, JIRA, Agile Lead',
    currentCompany: 'Cognizant Technology Solutions',
    currentCtc: '24 LPA',
    expectedCtc: '30 LPA',
    noticePeriod: '15 Days (Serving)',
    currentLocation: 'Hyderabad',
    preferredLocation: 'Hyderabad / Remote',
    interviewAvailability: 'Available weekdays after 4 PM',
    reasonForChange: 'Career Advancement & Technical Leadership',
    offerInHand: 'Yes (28 LPA from Capgemini)',
    resumeReference: 'Priyanka_Sharma_TestManager_Resume.pdf',
    notes: 'Exceptional communication skills, managed team of 14 QA engineers across US & India shifts.',
  },
  {
    id: '2',
    candidateId: '18015',
    name: 'VISHWATEJA THOPARAM',
    email: 'vishwateja.t@gmail.com',
    phone: '+91 98765 49457',
    technology: 'QA Automation Engineer, SDET, Full-Stack Tester',
    totalExperience: '5 Years 3 Months',
    relevantExperience: '5 Years',
    createdDate: '12 Aug 2026',
    createdBy: 'lakshmi.v Recruiter',
    status: 'New Profile',
    qualification: 'B.E. Computer Science, Osmania University',
    skills: 'Java, Selenium WebDriver, TestNG, Cucumber, REST Assured, Cypress, Playwright, Jenkins',
    currentCompany: 'Infosys Limited',
    currentCtc: '11.5 LPA',
    expectedCtc: '16 LPA',
    noticePeriod: '30 Days',
    currentLocation: 'Bangalore',
    preferredLocation: 'Bangalore / Hyderabad / Hybrid',
    interviewAvailability: 'Anytime with 1 day prior notice',
    reasonForChange: 'Looking for product-based company environment',
    offerInHand: 'No',
    resumeReference: 'Vishwateja_SDET_Resume.pdf',
    notes: 'Hands-on framework setup from scratch. Solid coding in Java & TypeScript.',
  },
  {
    id: '3',
    candidateId: '18014',
    name: 'SHILPA R',
    email: 'shilpa.r@gmail.com',
    phone: '+91 99887 76998',
    technology: 'Storage, Virtualization, Ha-Ft Systems',
    totalExperience: '5 Years 1 Month',
    relevantExperience: '4.8 Years',
    createdDate: '12 Aug 2026',
    createdBy: 'lakshmi.v Recruiter',
    status: 'Submitted to Client',
    qualification: 'B.Tech Information Technology, VTU Belgaum',
    skills: 'VMware ESXi, SAN/NAS Storage, NetApp, RedHat Linux, High Availability, Shell Scripting',
    currentCompany: 'Wipro Technologies',
    currentCtc: '13 LPA',
    expectedCtc: '18 LPA',
    noticePeriod: 'Immediate',
    currentLocation: 'Bangalore',
    preferredLocation: 'Bangalore',
    interviewAvailability: 'Immediate (Immediate joiner)',
    reasonForChange: 'Project buyout completed, looking for immediate placement',
    offerInHand: 'In Pipeline',
    resumeReference: 'Shilpa_R_StorageVirt_Resume.pdf',
    notes: 'Verified L3 storage support background. Clear background check record.',
  },
  {
    id: '4',
    candidateId: '18013',
    name: 'Varun kumar B H',
    email: 'varunkumar.bh@gmail.com',
    phone: '+91 97654 36912',
    technology: 'Qa Manual, Automation Software Test Engineer',
    totalExperience: '4 Years 7 Months',
    relevantExperience: '4.5 Years',
    createdDate: '12 Aug 2026',
    createdBy: 'lakshmi.v Recruiter',
    status: 'Submitted to Client',
    qualification: 'B.E. Electronics & Communication, RVCE Bangalore',
    skills: 'Python, PyTest, API Testing, Postman, SQL, Git, Charles Proxy, Mobile App Testing',
    currentCompany: 'Mindtree / LTIMindtree',
    currentCtc: '9.8 LPA',
    expectedCtc: '14 LPA',
    noticePeriod: '30 Days',
    currentLocation: 'Mysore',
    preferredLocation: 'Bangalore / Mysore',
    interviewAvailability: 'Weekdays after 6 PM',
    reasonForChange: 'Relocation to Bangalore preferred',
    offerInHand: 'No',
    resumeReference: 'VarunKumar_QA_Resume.pdf',
    notes: 'Experience with healthcare & fintech web & mobile apps.',
  },
  {
    id: '5',
    candidateId: '18012',
    name: 'AKASH MAHADEV TALBAR',
    email: 'akash.talbar@gmail.com',
    phone: '+91 98112 26236',
    technology: 'Biw, Sheet Metal Product Design',
    totalExperience: '5 Years 4 Months',
    relevantExperience: '5 Years',
    createdDate: '12 Aug 2026',
    createdBy: 'rahimoon Shaik',
    status: 'Interview Scheduled',
    qualification: 'B.E. Mechanical Engineering, Pune University',
    skills: 'CATIA V6, NX CAD, BIW Closures, Sheet Metal Forming, GD&T, Surfacing, Master Section Creation',
    currentCompany: 'Tata Technologies Ltd',
    currentCtc: '10.5 LPA',
    expectedCtc: '15 LPA',
    noticePeriod: '60 Days (Negotiable to 30 days)',
    currentLocation: 'Pune',
    preferredLocation: 'Pune / Chennai / Remote',
    interviewAvailability: 'Saturdays or weekdays 2 PM - 4 PM',
    reasonForChange: 'Better compensation & global automotive project exposure',
    offerInHand: 'No',
    resumeReference: 'Akash_Talbar_BIW_Design.pdf',
    notes: 'Worked on 2 complete vehicle OEM life cycle projects for European clients.',
  },
  {
    id: '6',
    candidateId: '18011',
    name: 'KUNDETI PRATHYUSHA',
    email: 'prathyusha.k@gmail.com',
    phone: '+91 94401 28955',
    technology: 'Manual Testing, Automation Testing',
    totalExperience: '5 Years',
    relevantExperience: '4 Years',
    createdDate: '12 Aug 2026',
    createdBy: 'lakshmi.v Recruiter',
    status: 'Submitted to Client',
    qualification: 'B.Tech Computer Science, JNTU Hyderabad',
    skills: 'Manual Testing, Functional & Regression Testing, Selenium Java, SQL Queries, JIRA Xray',
    currentCompany: 'Tech Mahindra',
    currentCtc: '8.5 LPA',
    expectedCtc: '13 LPA',
    noticePeriod: 'Immediate (Buyout available)',
    currentLocation: 'Hyderabad',
    preferredLocation: 'Hyderabad',
    interviewAvailability: 'Immediate availability',
    reasonForChange: 'Immediate joiner opportunity sought',
    offerInHand: 'Yes (11.5 LPA)',
    resumeReference: 'Kundeti_Prathyusha_QA.pdf',
    notes: 'Excellent team player, certified ISTQB Foundation level.',
  },
  {
    id: '7',
    candidateId: '18010',
    name: 'AMIT KULKARNI',
    email: 'amit.kulkarni@gmail.com',
    phone: '+91 98450 17712',
    technology: 'Software Engineering / C# Automation',
    totalExperience: '6 Years',
    relevantExperience: '5.5 Years',
    createdDate: '12 Aug 2026',
    createdBy: 'rahimoon Shaik',
    status: 'Shortlisted',
    qualification: 'B.E. Computer Science, BMS College of Engineering',
    skills: 'C#, .NET Core, SpecFlow, NUnit, Embedded Systems Testing, WPF Automation, CI/CD Azure DevOps',
    currentCompany: 'Bosch Global Software Technologies',
    currentCtc: '14.5 LPA',
    expectedCtc: '20 LPA',
    noticePeriod: '30 Days',
    currentLocation: 'Bangalore',
    preferredLocation: 'Bangalore / Mysore',
    interviewAvailability: 'Weekdays anytime with 2 hrs prior notice',
    reasonForChange: 'Project conclusion & seeking C# automation specialist role',
    offerInHand: 'No',
    resumeReference: 'Amit_Kulkarni_CSharp_Automation.pdf',
    notes: 'Deep domain expertise in C# automation & embedded hardware-in-loop testing.',
  },
]